### ISSUE TITLE
priority range and indifferent/random priority

### ISSUE THREAD

**Issue by montoyamoraga** [mitmedialab/opera-timeline#1]
i saw the tag p for priority, and i was wondering about the range of priority:

* is it just integer numbers, if so, what is the maximum?
* what happens with priority 0?
* can we specify events with an indifferent priority, as in, it doesn't matter? so if two events have this indifferent priority, pick one at random.
** could that behavior be priority -1 or 0?
** should that behavior be the default one?

**Comment by CharlesHolbrow** [comment]
The priority is just a JavaScript Number so it can be floating point, or you can keep all your numbers integers. How you intemperate is up to you. 

- There is no maximum or minimum
- 0 is an acceptable priority. It will have precedence over negative numbers, 
- Currently if two events have equal priority, the behavior is undefined, one will be chosen, but not totally at random. It will probably be the one that is included in your YAML first, but this is not guaranteed. 

See how events are hiding algorithm here: https://github.com/CharlesHolbrow/d3-media-timeline/blob/2f237eaad70adf0eec32e55f3b36c38ce0e82a09/src/timeline.mjs#L166-L188

For my timeline I use a 0-10 scale, but I chose this arbitrarily. You just have to make sure that each timeline is internally consistent :)
